// 4. How many unique brands are present in the collection?
// Output Sample is below the query.

// Select the database to use.
use('nikhil_ahlawat');

// Using disctinct() to find unique items in collection.
printjson (db.flipkart.distinct("brand"));


// OUTPUT


/*

Atlas atlas-ulggsn-shard-0 [primary] nikhil_ahlawat> load("./Desktop/nikhil_ahlawat/queries/query4.js")
[
  '16ARLINGTON',
  '3.1 PHILLIP LIM',
  'A EMERY',
  'A.L.C.',
  'A.W.A.K.E. MODE',
  'AAIZÉL',
  'AARMY',
  'ACNE STUDIOS',
  'ADAM LIPPES',
  'ADIDAS ORIGINALS',
  'AEYDE',
  'AGOLDE',
  'AGUA BY AGUA BENDITA',
  'AKRIS',
  'ALAÏA',
  'ALEX MILL',
  'ALEX PERRY',
  'ALEXANDER MCQUEEN',
  'ALEXANDER WANG',
  'ALEXANDERWANG.T',
  'ALEXANDRE BIRMAN',
  'ALICE + OLIVIA',
  'ALIX NYC',
  'ALTUZARRA',
  'AMINA MUADDI',
  'ANCIENT GREEK SANDALS',
  'ANDREA ADAMO',
  'ANINE BING',
  'ANN DEMEULEMEESTER',
  'ANNA QUAN',
  'APIECE APART',
  'APL ATHLETIC PROPULSION LABS',
  'AQUAZZURA',
  'ARCH4',
  'AREA',
  'ASHISH',
  'ATM ANTHONY THOMAS MELILLO',
  'ATP ATELIER',
  'AZ FACTORY',
  'BALENCIAGA',
  'BALMAIN',
  'BASERANGE',
  'BATSHEVA',
  'BENCHELLAL',
  'BERNADETTE',
  'BIRKENSTOCK 1774',
  'BOGNER',
  'BOTTEGA VENETA',
  'BOUGUESSA',
  'BRANDON MAXWELL',
  'BRUNELLO CUCINELLI',
  'BURBERRY',
  'BY FAR',
  'CAES',
  'CALLE DEL MAR',
  'CAMI NYC',
  'CAMILLA',
  'CANADA GOOSE',
  'CARAVANA',
  'CAROLINA HERRERA',
  'CAROLINE CONSTAS',
  'CECILIE BAHNSEN',
  'CEFINN',
  'CHARO RUIZ',
  'CHARVET',
  'CHLOÉ',
  'CHRISTIAN LOUBOUTIN',
  'CHRISTOPHER ESBER',
  'CHRISTOPHER KANE',
  'CITIZENS OF HUMANITY',
  'CO',
  'COMMON PROJECTS',
  'CONNER IVES',
  'CONVERSE',
  'COPERNI',
  'COSTARELLOS',
  'CULT GAIA',
  'DAVID KOMA',
  'DEADWOOD',
  'DIANE VON FURSTENBERG',
  'DION LEE',
  'DODO BAR OR',
  'DRIES VAN NOTEN',
  'DÔEN',
  'ELIE SAAB',
  'EMILIA WICKSTEAD',
  'EMILIO PUCCI',
  'EMME PARSONS',
  'EMPORIO SIRENUSE',
  'ENVELOPE1976',
  'ERDEM',
  'ERES',
  'ETRO',
  'EXTREME CASHMERE',
  'FAITHFULL THE BRAND',
  'FENDI',
  'FIL DE VIE',
  'FRAME',
  'FRANCES DE LOURDES',
  'FRANKIE SHOP',
  ... 176 more items
]

*/